pioneer_log: "test_pioneer.log"
jobs:
    steps:
        - name: run_test_script_1
          run: test/test1.json
          with: gui-runner
        - name: run_test_script_2
          run: test/test2.json
          with: web-runner
        - name: run_test_script_3
          run: test/test3.json
          with: api-runner
        - name: run_test_script_4
          run: test/test4.json
          with: load-runner
        - name: open_test_program
          open_program: test_path/test_file
          redirect_stdout: "test_std.log"
          redirect_stderr: "test_err.log"
        - name: wait_seconds
          wait: 5
        - name: open_test_url
          open_url: https://www.google.com
        - name: close_test_program
          close_program: open_test_program
