name: AutomationEditor Dev Python3.10

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: read

jobs:
  build_dev_version:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Update pip wheel setuptools
      run: python -m pip install --upgrade --user pip setuptools wheel
    - name: Run pip dev_requirements.txt
      run: python -m pip install --user -r dev_requirements.txt
    - name: Run AutomationEditor With Debug Mode
      run: python ./test/unit_test/start_automation/start_automation_test.py
    - name: Extend AutomationEditor
      run: python ./test/unit_test/start_automation/extend_automation_test.py

